<#
    PreToolUse hook task-mcp-role-guard (PLAT-3577, target design task-mcp-target section 6.1 R-3, N7), registered in
    .claude/settings.json on matcher mcp__aye-task(-lead)?__.* and only installed when the repo config sets "task_mcp".
    Source: tools/claude-kit/templates/hooks, rendered per repo by install.py.

    Purpose: guard rail against misuse, NOT a security boundary (R-6, R7: all agents run under the same Windows
    account). Each agent has its own inline aye-task server whose --role and --profile are fixed in its agent file
    (way A, PLAT-3480); the hook checks, per call, that the caller may use that server at all.

    Input: the JSON hook input on stdin. Mapping: task-mcp-roles.json next to this script, generated by install.py
    from the same table as the agent files (agent_type -> expected role and profile, tools per profile from the
    contract, settable status values).

    Identity (probe PLAT-3534, same logic as lead-write-guard): the main session NEVER has the key agent_id, a
    subagent always has it (even empty or null). Main session without agent_type counts as the lead.

    Deny (exit 2, reason on stderr, names the right way) when
      - agent_id is present and agent_type is missing, empty or not a string (missing-agent-type),
      - agent_type is present but empty or not a string (invalid-agent-type),
      - a subagent claims the lead agent_type (lead-in-subagent; the lead server belongs to the main session),
      - a subagent calls a tool of the lead server mcp__aye-task-lead__* (lead-server-in-subagent, PLAT-3715),
      - agent_type is not in the mapping, i.e. unknown or without a profile (unknown-agent-type, N7),
      - the tool is not in the profile of the expected role (tool-not-in-profile, wrong role),
      - task_set_status carries a status outside the settable list (status-not-settable, W-2 content check),
      - tool_input carries a key override_reason at any depth (override-reason, PLAT-3738 / Security S-3 part 1; all callers
        including the main session; the Task-CLI counterpart is task-call-guard).
    Changes to task_mcp.capabilities in tools/claude-kit/repos/<repo>.json move implement/review rights and need a
    security review (PLAT-3738).
    agent_type is compared ordinal and case-sensitive. Allow: exit 0 without output.

    Fail closed: any internal error (invalid JSON, wrong field types, missing or invalid mapping) is exit 2.
    No log, no input rewriting, no tool_input content in the output (only the status value, shortened).
#>
$ErrorActionPreference = 'Stop'
$ToolPrefix = 'mcp__aye-task__'
$LeadToolPrefix = 'mcp__aye-task-lead__'   # PLAT-3715: own name for the main-session (lead) server
$script:Fallback = ''

function Stop-Hook([string]$Code, [string]$Detail) {
    $fb = if ($script:Fallback) { " Bis dahin: Task-CLI ueber den Wrapper ($script:Fallback `"<Befehl>`")." } else { '' }
    $msg = "[task-mcp-role-guard] Abgelehnt ($Code): $Detail " +
        "Regel (Leitplanke gegen Fehlbedienung, keine Sicherheitsgrenze): mcp__aye-task__* nutzt jede Rolle nur ueber den Server in ihrer eigenen Agentendefinition, mcp__aye-task-lead__* nur die Hauptsession; " +
        "Lead-Werkzeuge (task_create, task_update_fields, task_add_dependency, task_add_evidence, task_cancel, task_replace_notes) gehoeren nur der Projektleitung (Hauptsession). " +
        "Richtiger Weg: Aenderungen ausserhalb deines Profils als Vorschlag im Uebergabebericht an die Projektleitung melden; fehlt der Server oder die Rolle ist unbekannt, die Kit-Konfiguration (task_mcp) pruefen lassen.$fb"
    [Console]::Error.WriteLine($msg)
    exit 2
}

# PLAT-3738 (Security S-3 part 1, ADR-0112): override_reason is the human path of the service (stored and counted); an
# agent call never carries it. The tool schemas have no such field (additionalProperties false), the hook names the rule
# before the service answers with a generic validation error. Keys only (any depth, case-insensitive, '-' or '_'),
# never values: notes may mention the word. Too deep nesting is treated as a hit (fail closed).
function Test-OverrideKey([object]$Node, [int]$Depth) {
    if ($Depth -gt 8) { return $true }
    if ($Node -is [System.Management.Automation.PSCustomObject]) {
        foreach ($p in $Node.PSObject.Properties) {
            if ($p.Name -match '(?i)^override[_-]?reason$') { return $true }
            if (Test-OverrideKey $p.Value ($Depth + 1)) { return $true }
        }
    } elseif ($Node -is [System.Collections.IEnumerable] -and $Node -isnot [string]) {
        foreach ($item in $Node) { if (Test-OverrideKey $item ($Depth + 1)) { return $true } }
    }
    return $false
}

function Get-Short([object]$Value) {
    if ($Value -isnot [string]) { return '<kein String>' }
    $s = $Value -replace '[^\x20-\x7E]', '?'
    if ($s.Length -gt 60) { $s = $s.Substring(0, 60) + '...' }
    return $s
}

try {
    $stdin = New-Object System.IO.MemoryStream
    [Console]::OpenStandardInput().CopyTo($stdin)
    $text = (New-Object System.Text.UTF8Encoding($false, $true)).GetString($stdin.ToArray()).TrimStart([char]0xFEFF)
    $data = $text | ConvertFrom-Json
    if ($data -isnot [System.Management.Automation.PSCustomObject]) { throw 'Hook-Eingabe ist kein JSON-Objekt' }
    if ($data.tool_name -isnot [string] -or $data.tool_name -eq '') { throw 'tool_name fehlt oder ist kein String' }
    $tool = $data.tool_name
    $isLeadServer = $tool.StartsWith($LeadToolPrefix, [StringComparison]::Ordinal)
    if ($isLeadServer) {
        $short = $tool.Substring($LeadToolPrefix.Length)
    } elseif ($tool.StartsWith($ToolPrefix, [StringComparison]::Ordinal)) {
        $short = $tool.Substring($ToolPrefix.Length)
    } else {
        exit 0
    }

    if (Test-OverrideKey $data.tool_input 0) {
        Stop-Hook 'override-reason' "Das Feld override_reason gehoert dem menschlichen Weg des Services (Task-CLI oder REST durch Sascha) und kommt in keinem Agent-Aufruf vor. Tool: $short. Stattdessen den Fehlertext des Services befolgen, den richtigen Weg gehen oder die Entscheidung an Sascha melden."
    }

    $mapPath = Join-Path $PSScriptRoot 'task-mcp-roles.json'
    $map = (Get-Content -LiteralPath $mapPath -Raw -Encoding UTF8) | ConvertFrom-Json
    if ($map -isnot [System.Management.Automation.PSCustomObject] -or $map.schema -ne 1) { throw 'Zuordnung task-mcp-roles.json ungueltig' }
    if ($map.lead_agent_type -isnot [string] -or $map.lead_agent_type -eq '') { throw 'lead_agent_type fehlt' }
    if ($map.fallback -is [string]) { $script:Fallback = $map.fallback }
    $lead = $map.lead_agent_type

    $keys = @($data.PSObject.Properties.Name)
    $hasId = $keys -ccontains 'agent_id'
    $type = $null
    if ($keys -ccontains 'agent_type') {
        $t = $data.agent_type
        if ($t -isnot [string] -or $t.Trim() -eq '') {
            if ($hasId) { Stop-Hook 'missing-agent-type' "Subagent-Aufruf (agent_id vorhanden) ohne gueltigen agent_type; die Rolle ist nicht pruefbar. Tool: $short." }
            Stop-Hook 'invalid-agent-type' "agent_type ist leer oder kein String. Tool: $short."
        }
        $type = $t
    }
    if ($hasId) {
        if ($null -eq $type) { Stop-Hook 'missing-agent-type' "Subagent-Aufruf (agent_id vorhanden) ohne agent_type; die Rolle ist nicht pruefbar. Tool: $short." }
        if ($type -ceq $lead) { Stop-Hook 'lead-in-subagent' "Ein Subagent meldet sich als $lead; der Lead-Server gehoert nur der Hauptsession. Tool: $short." }
        if ($isLeadServer) { Stop-Hook 'lead-server-in-subagent' "Der Lead-Server aye-task-lead gehoert nur der Hauptsession; ein Subagent (agent_type '$(Get-Short $type)') nutzt nur seinen eigenen Server aye-task. Tool: $short." }
    } elseif ($null -eq $type) {
        $type = $lead   # Hauptsession ohne agent_type gilt als Lead (Logik wie lead-write-guard)
    }

    $entry = $null
    foreach ($p in $map.agents.PSObject.Properties) { if ($p.Name -ceq $type) { $entry = $p.Value } }
    if ($null -eq $entry -or $entry.role -isnot [string] -or $entry.profile -isnot [string]) {
        Stop-Hook 'unknown-agent-type' "agent_type '$(Get-Short $type)' ist nicht in der Kit-Zuordnung (unbekannt oder ohne aye-task-Profil). Tool: $short."
    }
    $allowed = $null
    foreach ($p in $map.profile_tools.PSObject.Properties) { if ($p.Name -ceq $entry.profile) { $allowed = @($p.Value) } }
    if ($null -eq $allowed) { throw "Profil $($entry.profile) fehlt in profile_tools" }
    if ($allowed -cnotcontains $short) {
        Stop-Hook 'tool-not-in-profile' "Das Werkzeug $short gehoert nicht zum Profil $($entry.profile) der erwarteten Rolle $($entry.role) (agent_type '$(Get-Short $type)')."
    }

    if ($short -ceq 'task_set_status') {
        if ($data.tool_input -isnot [System.Management.Automation.PSCustomObject]) { Stop-Hook 'status-not-settable' 'tool_input fehlt oder ist kein Objekt (task_set_status).' }
        $st = $data.tool_input.status
        if ($st -isnot [string] -or @($map.settable_status) -cnotcontains $st) {
            Stop-Hook 'status-not-settable' "task_set_status setzt nur $(@($map.settable_status) -join ', '); Status '$(Get-Short $st)' ist nicht erlaubt (done nur ueber Complete-Task nach Review, cancelled nur ueber task_cancel der Projektleitung)."
        }
    }
    exit 0
} catch {
    [Console]::Error.WriteLine('[task-mcp-role-guard] interner Fehler, fail-closed (exit 2): ' + ($_.Exception.Message -replace '[^\x20-\x7E]', '?'))
    exit 2
}
